### PR TITLE
Corrects #1261 by specifying binary encoding

### PR DESCRIPTION
**Pull request by brian-learningpool**
@ryansmith94, here is the PR as promised.  Note that this is also dependent on the linked PR (https://github.com/feross/string-to-stream/pull/7) on the `string-to-stream` package.

It's been tested with local and S3 storage.

### CODE REVIEW

**Comment by brian-learningpool** [comment]
Big thanks to @wobrien for the testing and relentless debugging!

**Comment by ryansmith94** [comment]
Thanks @brian-learningpool and @wobrien! 👍 Was attachment retrieval via the API tested, I can probably check that out if not?

**Comment by brian-learningpool** [comment]
Hi @ryansmith94, attachment retrieval was found to work with `local` storage but there is a related ticket for `S3` (see [issue 1264](https://github.com/LearningLocker/learninglocker/issues/1264)).  

We haven't tested Google.

**Comment by ryansmith94** [comment]
Okay thanks @brian-learningpool 👍

**Comment by ryansmith94** [comment]
Since we're waiting on the string-to-stream maintainer to merge your fix, we may want to consider alternative packages rather than forking the repository. My concern with forking the repository is that we're then responsible for keeping that maintained. Below are a list of alternative packages we could consider, I'm not sure if they support encoding, but they seem to have more recent contributions.

- https://www.npmjs.com/package/into-stream
- https://www.npmjs.com/package/to-readable-stream

**Comment by ryansmith94** [comment]
Hey @brian-learningpool, there was an issue with Github which caused a CircleCI outage when this PR was made, unfortunately I can't make empty commits to this PR, could you please run the command below on this branch to trigger a CircleCI build?

```sh
git commit --allow-empty -m "ci(circle): Triggers build."
```

**Comment by brian-learningpool** [comment]
Hi @ryansmith94, I've just run that command.

**Comment by ryansmith94** [comment]
Thanks @brian-learningpool, unfortunately that doesn't seem to have made a difference, looks like CircleCI just isn't going to track this PR, would you be able to close this PR and make a new one? Sorry for the inconvenience.

**Comment by ryansmith94** [comment]
Hi @brian-learningpool, I've merged this into a new learning-pool branch so that we can get this merged now CircleCI seems to be working again.

**Pull request merged**
